from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "CLO_SKET_IVC_Manuscript.md"

# Canonical IVC submission sources only. Do not assemble from the legacy
# CLO_SKET_Final_* files; those are retained for provenance/archive purposes.
SECTIONS = [
    "CLO_SKET_IVC_Abstract.md",
    "CLO_SKET_IVC_Introduction.md",
    "CLO_SKET_IVC_Related_Work.md",
    "CLO_SKET_IVC_Methods.md",
    "CLO_SKET_IVC_Methods_Experiment_07.md",
    "CLO_SKET_IVC_Results.md",
    "CLO_SKET_IVC_Results_Experiment_07.md",
    "CLO_SKET_IVC_Discussion.md",
    "CLO_SKET_IVC_Discussion_Experiment_07.md",
    "CLO_SKET_IVC_Conclusion.md",
]

FRONT_MATTER = r'''# Garment Sketches: Axial–Radial Geometry and Identity-Aware Validation

> **Submission front matter to complete before journal upload**
>
> - Author names: [TO BE CONFIRMED]
> - Affiliations: [TO BE CONFIRMED]
> - Corresponding author and email: [TO BE CONFIRMED]
>
> **Source-of-truth rule:** the files listed in `SECTIONS` above are the canonical IVC scientific sources. `CLO_SKET_IVC_Manuscript.md` is generated from them and should not be edited independently. Legacy `CLO_SKET_Final_*`, `CLO_SKET_IVC_Main.md`, and files under `Reserve/` are retained only for provenance and comparison.

'''

DECLARATIONS = r'''

# Declarations

## Funding

[TO BE COMPLETED TRUTHFULLY BEFORE SUBMISSION]

## Competing interests

[TO BE COMPLETED TRUTHFULLY BEFORE SUBMISSION]

## Author contributions (CRediT)

[TO BE COMPLETED TRUTHFULLY BEFORE SUBMISSION]

## Acknowledgements

[TO BE COMPLETED IF APPLICABLE]

## Ethics statement

[TO BE COMPLETED IF REQUIRED BY THE JOURNAL; DO NOT ADD AN ETHICS APPROVAL CLAIM UNLESS APPLICABLE]

## Data and code availability

The image data analyzed in this study are from the publicly available CLO-SKET dataset released through Mendeley Data (Version 1; doi:10.17632/jt533nkhsf.1). The original images are not redistributed in this repository and should be obtained from the official dataset record.

Code, manuscript-supporting materials, and a compact reviewer-facing numerical evidence bundle are available in the public WeaveAI repository at https://github.com/nitikagupta1403/WeaveAI under `papers/CLO-SKET/`. The evidence bundle under `papers/CLO-SKET/evidence/` contains frozen Experiment 06 and Experiment 07 CSV/JSON results, fold-level summaries, out-of-fold predictions where applicable, identity-bootstrap records, manifests, provenance hashes, and `PUBLIC_EVIDENCE_MANIFEST.json` with byte sizes and SHA-256 hashes.

The public evidence bundle is intended for numerical audit and provenance verification rather than as a self-contained replacement for the original dataset or every frozen computational intermediate. The historical Experiment 06 runtime checkpoint and the 2,300 × 8,100 Experiment 07 HOG feature matrix are intentionally not redistributed through Git; the latter is a deterministic intermediate generated by the public Experiment 07 extraction code. No private image dataset or unpublished manual annotation is required for the reported analyses.
'''

REFERENCES_NOTE = r'''

# References

The canonical bibliography for journal typesetting is maintained in `CLO_SKET_References.bib`. Citation formatting should be generated from that file using the final Image and Vision Computing / Elsevier bibliography style rather than manually duplicating the bibliography here.
'''


def read_required(name: str) -> str:
    path = ROOT / name
    if not path.exists():
        raise FileNotFoundError(f"Required manuscript source is missing: {path}")
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        raise ValueError(f"Required manuscript source is empty: {path}")
    return text


def main() -> None:
    parts = [FRONT_MATTER.rstrip()]
    for name in SECTIONS:
        parts.append(read_required(name))
    parts.append(DECLARATIONS.strip())
    parts.append(REFERENCES_NOTE.strip())
    master = "\n\n---\n\n".join(parts) + "\n"
    OUT.write_text(master, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT.parent.parent)}")
    print(f"Characters: {len(master):,}")
    print(f"Canonical scientific source sections: {len(SECTIONS)}")


if __name__ == "__main__":
    main()
