from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "CLO_SKET_IVC_Manuscript.md"

# Canonical IVC submission sources only. Do not assemble from the legacy
# CLO_SKET_Final_* files; those are retained for provenance/archive purposes.
SECTIONS = [
    "CLO_SKET_IVC_Abstract.md",
    "CLO_SKET_IVC_Introduction.md",
    "CLO_SKET_IVC_Related_Work.md",
    "CLO_SKET_IVC_Methods.md",
    "CLO_SKET_IVC_Results.md",
    "CLO_SKET_IVC_Discussion.md",
    "CLO_SKET_IVC_Conclusion.md",
]

FRONT_MATTER = r'''# Garment Sketches: Axial–Radial Geometry and Identity-Aware Validation

**Nitika Gupta**

Independent Researcher, Hyderabad, Telangana, India

Corresponding author: Nitika Gupta, nitikashimla14@gmail.com

> **Source-of-truth rule:** the files listed in `SECTIONS` above are the canonical IVC scientific sources. `CLO_SKET_IVC_Manuscript.md` is generated from them and should not be edited independently. Legacy `CLO_SKET_Final_*`, `CLO_SKET_IVC_Main.md`, the standalone `CLO_SKET_IVC_*_Experiment_07.md` fragments, and files under `Reserve/` are retained only for provenance and comparison.

'''

DECLARATIONS = r'''

# Declarations

## Funding

No specific funding supported this research.

## Competing interests

The author declares no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper.

## Author contributions (CRediT)

Nitika Gupta: Conceptualization, Methodology, Software, Validation, Formal analysis, Investigation, Data curation, Visualization, Writing – original draft, Writing – review & editing.

## Acknowledgements

The author thanks the creators and maintainers of the publicly available CLO-SKET dataset.

## Ethics statement

This study analyzed a publicly available garment-sketch dataset and involved no human participants, animals, identifiable personal data, or intervention. Ethics approval and informed consent were therefore not applicable.

## Declaration of generative AI and AI-assisted technologies in the writing process

During preparation of this work, the author used ChatGPT and OpenAI Codex to assist with language editing, manuscript organization, and code and documentation review. The author reviewed and edited all resulting material and takes full responsibility for the content of the publication.

## Data and code availability

The image data analyzed in this study are from the publicly available CLO-SKET dataset released through Mendeley Data (Version 1; doi:10.17632/jt533nkhsf.1). The original images are not redistributed in this repository and should be obtained from the official dataset record.

Code, manuscript-supporting materials, and reviewer-facing numerical evidence are available in the public WeaveAI repository at https://github.com/nitikagupta1403/WeaveAI under `papers/CLO-SKET/`. The evidence bundle under `papers/CLO-SKET/evidence/` contains frozen Experiment 06 and Experiment 07 records together with the deposited Experiment-08 evidence under `evidence/Experiment_08/`. Experiment-08 executable materials are maintained under `Codes_paper_I/Experiment_08/`, and its evidence chronology is recorded in `docs/experiment-08/EXPERIMENT08_EVIDENCE_PROVENANCE_MANIFEST.md`. Experiment 08 failed its frozen mechanical gate; all subsequent Experiment-08 predictive results remain explicitly post-outcome / exploratory.

The public evidence bundle is intended for numerical audit and provenance verification rather than as a self-contained replacement for the original dataset or every frozen computational intermediate. The historical Experiment 06 runtime checkpoint and the 2,300 × 8,100 Experiment 07 HOG feature matrix are intentionally not redistributed through Git; the latter is a deterministic intermediate generated by the public Experiment 07 extraction code. `PUBLIC_EVIDENCE_MANIFEST.json` records the included Experiment 06 and Experiment 07 public evidence files, byte sizes, and SHA-256 hashes; Experiment-08 evidence is maintained separately under `evidence/Experiment_08/`. No private image dataset or unpublished manual annotation is required for the reported analyses.
'''

REFERENCES_FILE = "CLO_SKET_IVC_References.md"


def read_required(name: str) -> str:
    path = ROOT / name
    if not path.exists():
        raise FileNotFoundError(f"Required manuscript source is missing: {path}")
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        raise ValueError(f"Required manuscript source is empty: {path}")
    return text


def main() -> None:
    parts = [FRONT_MATTER.rstrip()]
    for name in SECTIONS:
        parts.append(read_required(name))
    parts.append(DECLARATIONS.strip())
    parts.append(read_required(REFERENCES_FILE))
    master = "\n\n---\n\n".join(parts) + "\n"
    OUT.write_text(master, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT.parent.parent)}")
    print(f"Characters: {len(master):,}")
    print(f"Canonical scientific source sections: {len(SECTIONS)}")


if __name__ == "__main__":
    main()
